apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: sockshop-backup
  namespace: kasten-io
spec:
  comment: API Based Backup
  frequency: '@hourly'
  retention:
    hourly: 24
    daily: 7
  actions:
  - action: backup
  selector:
    matchLabels:
      k10.kasten.io/appNamespace: sockshop
